# Generated by Django 2.2.4 on 2020-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
