# Generated by Django 2.2.4 on 2020-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0003_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='booksAuthorsApp.Authors'),
        ),
    ]
